# Generated by Django 4.0.4 on 2022-05-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_entry_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='owner',
        ),
    ]
